source $(pwd)/env.sh

psql -U $DB_USER_ROOT -p $DB_PORT -h $DB_HOST \
    -c "CREATE ROLE $DB_USER WITH PASSWORD '$DB_PASSWORD';"
psql -U $DB_USER_ROOT -p $DB_PORT -h $DB_HOST \
    -c "CREATE DATABASE $DB_NAME;"
psql -U $DB_USER_ROOT -p $DB_PORT -h $DB_HOST \
    -c "ALTER ROLE $DB_USER WITH LOGIN;"
psql -U $DB_USER_ROOT -p $DB_PORT -h $DB_HOST -d $DB_NAME \
    -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
psql -U $DB_USER_ROOT -p $DB_PORT -h $DB_HOST -d $DB_NAME \
    -c "GRANT CREATE ON SCHEMA public TO $DB_USER;"
